In [1]:
import numpy as np

### Array creation

In [2]:
a = np.array([1, 2, 3])

In [14]:
print(a)
print(a.shape)
print(a.reshape(-1, 3))

[1 2 3]
(3,)
[[1 2 3]]


In [15]:
b = np.array([(1, 2), (3, 4)])

In [22]:
print(b)
print(b.shape)
print(b.reshape(-1, 4))  # as row vector
print(b.reshape(4, -1))  # as col vector


[[1 2]
 [3 4]]
(2, 2)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


### Array filled with specific values

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3, 3)).astype(np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [31]:
np.full(shape=(2, 2), fill_value=10, dtype=np.float16)

array([[10., 10.],
       [10., 10.]], dtype=float16)

### Arrays with sequential values

In [34]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.linspace(0, 10,  30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

### Random arrays

In [39]:
# Random generator
rng = np.random.default_rng(42)

In [37]:
np.random.rand(2, 3)

array([[0.24285535, 0.88278998, 0.60920159],
       [0.68792011, 0.04603593, 0.71664644]])

In [47]:
rng.normal(size=(2, 3))

array([[-0.82448122,  0.65059279,  0.74325417],
       [ 0.54315427, -0.66550971,  0.23216132]])

In [59]:
np.random.randint(0, 10, (3, 3))

array([[2, 3, 8],
       [0, 0, 6],
       [0, 2, 3]], dtype=int32)

In [60]:
rng.integers(0, 10, (3, 3))

array([[4, 9, 2],
       [2, 4, 9],
       [8, 0, 2]])

### Array properties

In [62]:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)     
print(arr.ndim)      
print(arr.size)    
print(arr.dtype)     


(2, 2)
2
4
int64


### Ejercicio práctico 

**Objetivo**: Poner en práctica la creación de arrays y manipulación básica.

**Instrucciones**:
* Crea una matriz 3x4 con valores del 0 al 11.

* Cambia su forma a 4x3.

* Obtén una versión 1D de la matriz con flatten.

* Crea un array 3x3 de números aleatorios enteros entre 10 y 99.

* Extrae la propiedad shape, size, ndim y dtype de cada array.

* Usa np.linspace para crear un array de 8 valores equidistantes entre 0 y 1.

In [64]:
mat = np.array(
    [(0, 1, 2), (3, 4, 5), (6, 7, 8)]
)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
mat = np.random.randint(0, 11, size=(3, 3))
mat

array([[7, 5, 7],
       [2, 5, 4],
       [2, 9, 6]], dtype=int32)

In [86]:
# Crea una matriz 3x4 con valores del 0 al 11.

mat = np.arange(0, 12, 1).reshape(3, 4)
print(mat)
print(mat.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [89]:
# Cambia su forma a 4x3.

rmat = mat.reshape(4, -1)
print(rmat)
print(rmat.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [93]:
# Obtén una versión 1D de la matriz con flatten.
mat_flatten = mat.flatten()
mat_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
fmat = mat.reshape(1, -1)
fmat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [105]:
mat_flatten - fmat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [107]:
# Crea un array 3x3 de números aleatorios enteros entre 10 y 99.

rdm = np.random.randint(10, 99, size=(3, 3))
rdm

array([[96, 81, 31],
       [45, 68, 62],
       [23, 35, 51]], dtype=int32)

In [109]:
# Extrae la propiedad shape, size, ndim y dtype de cada array.

def info(arr: np.ndarray):
    return {
        'shape': arr.shape, 
        'size': arr.size,
        'ndim': arr.ndim,
        'dtype': arr.dtype
    }

In [110]:
print(info(rdm))

{'shape': (3, 3), 'size': 9, 'ndim': 2, 'dtype': dtype('int32')}


In [111]:
# Usa np.linspace para crear un array de 8 valores equidistantes entre 0 y 1.

eqarr = np.linspace(0, 1, 8)
eqarr

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

**Ejercicio 1**: Tablero de ajedrez (con ceros y unos)

Objetivo: Usar slicing para crear una matriz 8x8 tipo ajedrez, donde los valores alternen entre 0 y 1 como un tablero real.

In [142]:
board = np.zeros((8, 8), dtype=int)
board[::2, ::2] = 1
board[1::2, 1::2] = 1
board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**Ejercicio 2:** Normalización de una matriz

Objetivo: Normalizar una matriz 5x5 de valores aleatorios enteros entre 0 y 100.



In [146]:
mat = np.random.randint(0, 100, size=(5, 5))
mat

array([[35, 84, 53, 91, 85],
       [ 7, 28,  1,  5,  5],
       [98, 62, 47,  2, 17],
       [70, 71, 32, 45, 90],
       [37, 66, 29, 43, 43]], dtype=int32)

In [149]:
def normalize(x: np.ndarray): 
    return (x - x.min()) / (x.max() - x.min())

In [150]:
print(normalize(mat))

[[0.35051546 0.8556701  0.53608247 0.92783505 0.86597938]
 [0.06185567 0.27835052 0.         0.04123711 0.04123711]
 [1.         0.62886598 0.4742268  0.01030928 0.16494845]
 [0.71134021 0.72164948 0.31958763 0.45360825 0.91752577]
 [0.37113402 0.67010309 0.28865979 0.43298969 0.43298969]]


**Ejercicio 3:** Diagonal dominante

Objetivo: Crear una matriz cuadrada de tamaño 5x5 donde la diagonal principal tenga el valor 100, y el resto valores aleatorios entre 0 y 10.

In [157]:
mat = np.random.uniform(0, 10, size=(5, 5))
np.fill_diagonal(mat, 100)
mat

array([[100.        ,   2.60768015,   9.71943018,   5.89353042,
          6.88918761],
       [  7.80685548, 100.        ,   8.76144736,   7.62910926,
          9.56827664],
       [  2.73939895,   9.92925194, 100.        ,   1.58921179,
          4.07029081],
       [  9.53568932,   8.30870024,   3.316382  , 100.        ,
          6.69382906],
       [  7.00808862,   2.81548628,   9.23805043,   1.49667163,
        100.        ]])

**Ejercicio 4:** Encontrar la fila con mayor suma

Objetivo: Dada una matriz 6x4 de números enteros aleatorios entre 1 y 100, identificar:

* El índice de la fila con mayor suma

* El contenido de dicha fila

In [221]:
mat = np.random.randint(1, 100, size=(6, 4))
mat

array([[29, 28, 87, 68],
       [61, 31, 33,  7],
       [15, 30, 92, 43],
       [84, 72, 37, 45],
       [92, 35, 27, 29],
       [36, 73, 76, 43]], dtype=int32)

In [226]:
print(mat.sum(axis=1)) # Sum over the rows
print(mat.sum(axis=0)) # Sum the cols

[212 132 180 238 183 228]
[317 269 352 235]


In [223]:
def max_sum(x: np.ndarray): 
    row_sum = x.sum(axis=1)
    max_index = np.argmax(row_sum)
    return {
        'index': max_index, 
        'row': x[max_index]
    }

In [227]:
print(max_sum(mat))

{'index': np.int64(3), 'row': array([84, 72, 37, 45], dtype=int32)}


**Ejercicio 5**: Contar elementos bajo una condición

Objetivo: Dada una matriz aleatoria 10x10 de valores entre 0 y 1, contar:

* Cuántos elementos son mayores a 0.5

* Cuántos están entre 0.25 y 0.75 (inclusive)

In [183]:
mat = np.random.random(size=(10, 10))
mat

array([[0.08291273, 0.49820072, 0.68795749, 0.67877018, 0.49481859,
        0.21159774, 0.81283984, 0.19845363, 0.51264318, 0.60305853],
       [0.88995969, 0.93418162, 0.97428524, 0.16076067, 0.31812001,
        0.08161529, 0.67348334, 0.25773355, 0.01108229, 0.01212894],
       [0.98769276, 0.00691209, 0.80717259, 0.05918972, 0.97305761,
        0.16966328, 0.30556658, 0.84608208, 0.40613868, 0.08818913],
       [0.01639399, 0.39116717, 0.18375882, 0.84623617, 0.25353922,
        0.42466802, 0.36671558, 0.09404139, 0.54331455, 0.43154056],
       [0.68532528, 0.99409598, 0.68559213, 0.67112807, 0.41250674,
        0.49123728, 0.92859354, 0.79654039, 0.4714751 , 0.4248445 ],
       [0.86405472, 0.16788487, 0.26890072, 0.18117641, 0.82096899,
        0.19224574, 0.28140014, 0.9947003 , 0.52243194, 0.99492048],
       [0.35795773, 0.99554861, 0.85058268, 0.91889393, 0.73404538,
        0.47080634, 0.8979671 , 0.56158692, 0.86502468, 0.5960923 ],
       [0.89839718, 0.66362407, 0.5776957

In [184]:
# Cuántos elementos son mayores a 0.5
len(mat[mat > 0.5])

51

In [192]:
# The numpy way: 
np.sum(mat > 0.5)  # It counts the True values

np.int64(51)

In [187]:
# Cuántos están entre 0.25 y 0.75 (inclusive)
len(mat[(mat > 0.25) & (mat <= 0.75)])

47

In [188]:
np.sum((mat > 0.25) & (mat <= 0.75))

np.int64(47)

**Ejercicio 6**: Modificar una matriz sin loops

Objetivo: Crear una matriz 4x4 con valores del 0 al 15 y reemplazar todos los múltiplos de 3 con -1.


In [177]:
mat = np.arange(0, 16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [178]:
mat[mat % 3 == 0] = -1
mat  

array([[-1,  1,  2, -1],
       [ 4,  5, -1,  7],
       [ 8, -1, 10, 11],
       [-1, 13, 14, -1]])