In [1]:
import numpy as np

# Intro to NumPy

### Array creation

In [2]:
a = np.array([1, 2, 3])

In [14]:
print(a)
print(a.shape)
print(a.reshape(-1, 3))

[1 2 3]
(3,)
[[1 2 3]]


In [15]:
b = np.array([(1, 2), (3, 4)])

In [22]:
print(b)
print(b.shape)
print(b.reshape(-1, 4))  # as row vector
print(b.reshape(4, -1))  # as col vector


[[1 2]
 [3 4]]
(2, 2)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


### Array filled with specific values

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3, 3)).astype(np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [31]:
np.full(shape=(2, 2), fill_value=10, dtype=np.float16)

array([[10., 10.],
       [10., 10.]], dtype=float16)

### Arrays with sequential values

In [34]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.linspace(0, 10,  30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

### Random arrays

In [39]:
# Random generator
rng = np.random.default_rng(42)

In [37]:
np.random.rand(2, 3)

array([[0.24285535, 0.88278998, 0.60920159],
       [0.68792011, 0.04603593, 0.71664644]])

In [47]:
rng.normal(size=(2, 3))

array([[-0.82448122,  0.65059279,  0.74325417],
       [ 0.54315427, -0.66550971,  0.23216132]])

In [59]:
np.random.randint(0, 10, (3, 3))

array([[2, 3, 8],
       [0, 0, 6],
       [0, 2, 3]], dtype=int32)

In [60]:
rng.integers(0, 10, (3, 3))

array([[4, 9, 2],
       [2, 4, 9],
       [8, 0, 2]])

### Array properties

In [62]:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)     
print(arr.ndim)      
print(arr.size)    
print(arr.dtype)     


(2, 2)
2
4
int64


### Ejercicio práctico 

**Objetivo**: Poner en práctica la creación de arrays y manipulación básica.

**Instrucciones**:
* Crea una matriz 3x4 con valores del 0 al 11.

* Cambia su forma a 4x3.

* Obtén una versión 1D de la matriz con flatten.

* Crea un array 3x3 de números aleatorios enteros entre 10 y 99.

* Extrae la propiedad shape, size, ndim y dtype de cada array.

* Usa np.linspace para crear un array de 8 valores equidistantes entre 0 y 1.

In [64]:
mat = np.array(
    [(0, 1, 2), (3, 4, 5), (6, 7, 8)]
)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
mat = np.random.randint(0, 11, size=(3, 3))
mat

array([[7, 5, 7],
       [2, 5, 4],
       [2, 9, 6]], dtype=int32)

In [86]:
# Crea una matriz 3x4 con valores del 0 al 11.

mat = np.arange(0, 12, 1).reshape(3, 4)
print(mat)
print(mat.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [89]:
# Cambia su forma a 4x3.

rmat = mat.reshape(4, -1)
print(rmat)
print(rmat.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [93]:
# Obtén una versión 1D de la matriz con flatten.
mat_flatten = mat.flatten()
mat_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
fmat = mat.reshape(1, -1)
fmat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [105]:
mat_flatten - fmat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [107]:
# Crea un array 3x3 de números aleatorios enteros entre 10 y 99.

rdm = np.random.randint(10, 99, size=(3, 3))
rdm

array([[96, 81, 31],
       [45, 68, 62],
       [23, 35, 51]], dtype=int32)

In [109]:
# Extrae la propiedad shape, size, ndim y dtype de cada array.

def info(arr: np.ndarray):
    return {
        'shape': arr.shape, 
        'size': arr.size,
        'ndim': arr.ndim,
        'dtype': arr.dtype
    }

In [110]:
print(info(rdm))

{'shape': (3, 3), 'size': 9, 'ndim': 2, 'dtype': dtype('int32')}


In [111]:
# Usa np.linspace para crear un array de 8 valores equidistantes entre 0 y 1.

eqarr = np.linspace(0, 1, 8)
eqarr

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

**Ejercicio 1**: Tablero de ajedrez (con ceros y unos)

Objetivo: Usar slicing para crear una matriz 8x8 tipo ajedrez, donde los valores alternen entre 0 y 1 como un tablero real.

In [142]:
board = np.zeros((8, 8), dtype=int)
board[::2, ::2] = 1
board[1::2, 1::2] = 1
board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**Ejercicio 2:** Normalización de una matriz

Objetivo: Normalizar una matriz 5x5 de valores aleatorios enteros entre 0 y 100.



In [146]:
mat = np.random.randint(0, 100, size=(5, 5))
mat

array([[35, 84, 53, 91, 85],
       [ 7, 28,  1,  5,  5],
       [98, 62, 47,  2, 17],
       [70, 71, 32, 45, 90],
       [37, 66, 29, 43, 43]], dtype=int32)

In [149]:
def normalize(x: np.ndarray): 
    return (x - x.min()) / (x.max() - x.min())

In [150]:
print(normalize(mat))

[[0.35051546 0.8556701  0.53608247 0.92783505 0.86597938]
 [0.06185567 0.27835052 0.         0.04123711 0.04123711]
 [1.         0.62886598 0.4742268  0.01030928 0.16494845]
 [0.71134021 0.72164948 0.31958763 0.45360825 0.91752577]
 [0.37113402 0.67010309 0.28865979 0.43298969 0.43298969]]


**Ejercicio 3:** Diagonal dominante

Objetivo: Crear una matriz cuadrada de tamaño 5x5 donde la diagonal principal tenga el valor 100, y el resto valores aleatorios entre 0 y 10.

In [157]:
mat = np.random.uniform(0, 10, size=(5, 5))
np.fill_diagonal(mat, 100)
mat

array([[100.        ,   2.60768015,   9.71943018,   5.89353042,
          6.88918761],
       [  7.80685548, 100.        ,   8.76144736,   7.62910926,
          9.56827664],
       [  2.73939895,   9.92925194, 100.        ,   1.58921179,
          4.07029081],
       [  9.53568932,   8.30870024,   3.316382  , 100.        ,
          6.69382906],
       [  7.00808862,   2.81548628,   9.23805043,   1.49667163,
        100.        ]])

**Ejercicio 4:** Encontrar la fila con mayor suma

Objetivo: Dada una matriz 6x4 de números enteros aleatorios entre 1 y 100, identificar:

* El índice de la fila con mayor suma

* El contenido de dicha fila

In [221]:
mat = np.random.randint(1, 100, size=(6, 4))
mat

array([[29, 28, 87, 68],
       [61, 31, 33,  7],
       [15, 30, 92, 43],
       [84, 72, 37, 45],
       [92, 35, 27, 29],
       [36, 73, 76, 43]], dtype=int32)

In [226]:
print(mat.sum(axis=1)) # Sum over the rows
print(mat.sum(axis=0)) # Sum the cols

[212 132 180 238 183 228]
[317 269 352 235]


In [223]:
def max_sum(x: np.ndarray): 
    row_sum = x.sum(axis=1)
    max_index = np.argmax(row_sum)
    return {
        'index': max_index, 
        'row': x[max_index]
    }

In [227]:
print(max_sum(mat))

{'index': np.int64(3), 'row': array([84, 72, 37, 45], dtype=int32)}


**Ejercicio 5**: Contar elementos bajo una condición

Objetivo: Dada una matriz aleatoria 10x10 de valores entre 0 y 1, contar:

* Cuántos elementos son mayores a 0.5

* Cuántos están entre 0.25 y 0.75 (inclusive)

In [183]:
mat = np.random.random(size=(10, 10))
mat

array([[0.08291273, 0.49820072, 0.68795749, 0.67877018, 0.49481859,
        0.21159774, 0.81283984, 0.19845363, 0.51264318, 0.60305853],
       [0.88995969, 0.93418162, 0.97428524, 0.16076067, 0.31812001,
        0.08161529, 0.67348334, 0.25773355, 0.01108229, 0.01212894],
       [0.98769276, 0.00691209, 0.80717259, 0.05918972, 0.97305761,
        0.16966328, 0.30556658, 0.84608208, 0.40613868, 0.08818913],
       [0.01639399, 0.39116717, 0.18375882, 0.84623617, 0.25353922,
        0.42466802, 0.36671558, 0.09404139, 0.54331455, 0.43154056],
       [0.68532528, 0.99409598, 0.68559213, 0.67112807, 0.41250674,
        0.49123728, 0.92859354, 0.79654039, 0.4714751 , 0.4248445 ],
       [0.86405472, 0.16788487, 0.26890072, 0.18117641, 0.82096899,
        0.19224574, 0.28140014, 0.9947003 , 0.52243194, 0.99492048],
       [0.35795773, 0.99554861, 0.85058268, 0.91889393, 0.73404538,
        0.47080634, 0.8979671 , 0.56158692, 0.86502468, 0.5960923 ],
       [0.89839718, 0.66362407, 0.5776957

In [184]:
# Cuántos elementos son mayores a 0.5
len(mat[mat > 0.5])

51

In [192]:
# The numpy way: 
np.sum(mat > 0.5)  # It counts the True values

np.int64(51)

In [187]:
# Cuántos están entre 0.25 y 0.75 (inclusive)
len(mat[(mat > 0.25) & (mat <= 0.75)])

47

In [188]:
np.sum((mat > 0.25) & (mat <= 0.75))

np.int64(47)

**Ejercicio 6**: Modificar una matriz sin loops

Objetivo: Crear una matriz 4x4 con valores del 0 al 15 y reemplazar todos los múltiplos de 3 con -1.


In [177]:
mat = np.arange(0, 16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [178]:
mat[mat % 3 == 0] = -1
mat  

array([[-1,  1,  2, -1],
       [ 4,  5, -1,  7],
       [ 8, -1, 10, 11],
       [-1, 13, 14, -1]])

# Elementwise operations

**¿Qué son las operaciones elementwise?**

Cuando haces operaciones entre arrays del mismo shape, NumPy realiza la operación elemento a elemento sin necesidad de bucles explícitos.

**Operaciones soportadas (arrays del mismo tamaño)**:

* +, -, *, /, // (división entera), %, ** (potencia)

* np.add, np.subtract, np.multiply, np.divide → funciones equivalentes si necesitas mayor control

In [2]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)  # [11 22 33]
print(a * b)  # [10 40 90]
print(b / a)  # [10. 10. 10.]
print(a - 1)  # [0 1 2] (broadcasting con una constante)

[11 22 33]
[10 40 90]
[10. 10. 10.]
[0 1 2]


The term **Broadcasting** describes how NumPy trats arrays with different shapes during arithmetic operations.  

In [6]:
a = np.array([1, 2, 3])
a * 2 == np.multiply(a,2)

array([ True,  True,  True])

**Problema**: Simulación de puntajes de estudiantes

Supón que tienes las calificaciones de 5 estudiantes en dos exámenes diferentes. Cada uno tiene un puntaje entre 0 y 100.

Tu tarea es:

1. Crear dos arrays aleatorios de shape (5,) que representen las calificaciones de los estudiantes en dos exámenes diferentes.

2. Calcular el promedio por estudiante.

3. Aplicar una penalización del 10% al segundo examen.

4. Calcular el promedio final ajustado.

5. Determinar cuántos estudiantes aprobaron (promedio final ajustado ≥ 60).



In [68]:
# 1
test_1 = np.round(np.random.uniform(0, 100, size=5), 1)
test_2 = np.round(np.random.uniform(0, 100, size=5), 1)
print(test_1)
print(test_2)


[76.9 19.4 42.5 34.8 52.5]
[95.1 33.9 85.6 19.3 14.9]


In [69]:
# 2
avg_test = (test_1 + test_2) / 2
avg_test

array([86.  , 26.65, 64.05, 27.05, 33.7 ])

In [73]:
# 3 
test_2_pen = test_2 * 0.90
test_2_pen

array([85.59, 30.51, 77.04, 17.37, 13.41])

In [74]:
# 4 
avg_test_penalized = (test_1 + test_2_pen) / 2
avg_test_penalized 

array([81.245, 24.955, 59.77 , 26.085, 32.955])

In [75]:
# 5
print('Total of Approved Students: ', np.sum(avg_test_penalized > 60))

Total of Approved Students:  1


**Ejercicio 1**: Normalización por columnas con broadcasting

Tienes una matriz X de shape (100, 5) que representa 100 muestras con 5 características numéricas.

Tu tarea:
1. Genera X con valores aleatorios entre 0 y 100.

2. Normaliza cada columna usando min-max scaling
3. Verifica que el valor mínimo por columna sea 0 y el máximo sea 1.

In [94]:
sample_data = np.random.randint(0, 100, (3, 3))
sample_data

array([[ 5, 39, 83],
       [38, 99, 28],
       [28, 62, 43]], dtype=int32)

In [103]:
min_ = sample_data.min(axis=0)
min_

array([ 5, 39, 28], dtype=int32)

In [107]:
sample_data - min_

array([[ 0,  0, 55],
       [33, 60,  0],
       [23, 23, 15]], dtype=int32)

In [106]:
sample_data - min_.reshape(3, 1)

array([[  0,  34,  78],
       [ -1,  60, -11],
       [  0,  34,  15]], dtype=int32)

In [95]:
def normalize_b(X: np.ndarray):
    min_ = X.min(axis=0)
    max_ = X.max(axis=0)
    return (X - min_) / (max_ - min_)

In [108]:
norm_data = normalize_b(sample_data)
norm_data

array([[0.        , 0.        , 1.        ],
       [1.        , 1.        , 0.        ],
       [0.6969697 , 0.38333333, 0.27272727]])

**Ejercicio 2**: Costo cuadrático medio (MSE) entre predicciones

Simula una situación de modelo de regresión.

Tu tarea:
1. Crea dos arrays `y_true` y `y_pred` de 100 elementos con valores aleatorios entre 0 y 1.

2. Calcula el error cuadrático medio (MSE):

3. Si el MSE es mayor a 0.05, imprime “Modelo inaceptable”, si no, imprime “Modelo aceptable”.

In [5]:
y_true = np.random.uniform(0, 1, 100)
y_pred = np.random.uniform(0, 1, 100)
# print(y_true)
# print(y_pred)

In [6]:
def mse(y_pred: np.ndarray, y_true: np.ndarray): 
    n = len(y_pred)
    return (1/n) * np.sum(y_true - y_pred)** 2 

In [10]:
mse_val = mse(np.random.uniform(0, 1, 100), np.random.uniform(0, 1, 100))
if mse_val > 0.05: 
    print('Modelo inaceptable', mse_val)
else: 
    print('Modelo Aceptable', mse_val)

Modelo Aceptable 0.02408441633338904


**Ejercicio 3:** Clasificación con umbral variable

Tienes predicciones continuas (`y_prob`) y deseas clasificarlas en 0 o 1 según un umbral que cambia por grupo.

Tu tarea:
1. Crea un array y_prob de shape (12,) con valores entre 0 y 1.

2. Crea un array thresholds de shape (4,) con valores [0.3, 0.5, 0.7, 0.9].

3. Divide y_prob en 4 grupos de 3 valores. Para cada grupo, aplica su respectivo threshold: si el valor es mayor al umbral, se clasifica como 1, si no 0.

3. Obtén un array de clasificaciones de shape (12,).



In [133]:
np.random.random(12).shape

(12,)

In [134]:
y_prob_test = np.random.random(12)

In [ ]:
def classify(data: np.ndarray):
    thresh = np.array([0.3, 0.5, 0.7, 0.9])
    

# Indexing and Slicing

In [18]:
# Unidimensional and multidimensional slicing

a = np.array([10, 20, 30])
print(a[0])

b = np.array([[1, 2], [3, 4]])
print(b[0, 1])

10
2


In [27]:
# Slicing
print(a[1:])  # from the first
print()
print(b[:, 1])  # second col
print()
print(b[0, :])  # first row
print()
print(b[0:2, 0:2])  # submatrix

[20 30]

[2 4]

[1 2]

[[1 2]
 [3 4]]


In [28]:
a[::-1]  # row reverse

array([30, 20, 10])

In [30]:
b[::-1, ::-1] # matrix reverse

array([[4, 3],
       [2, 1]])

In [31]:
# Fancy indexing
b[[0, 1], [1, 0]]  # b[0,1] and b[1,0]

array([2, 3])

**Práctica**: Extracción de submatrices

Supón que tienes una imagen en escala de grises representada como una matriz 2D de tamaño (10, 10) con valores entre 0 y 255.

Tu tarea:

1. Crea una matriz img de np.random.randint(0, 256, (10, 10)).
2. Extrae la esquina superior izquierda (submatriz de 3x3).
3. Extrae la fila central completa.
4. Extrae la columna derecha completa.
5. Extrae el cuadro central de 4x4.
6. Crea una versión espejada horizontalmente de la imagen.
7. Crea una versión rotada 90° en sentido horario.

*Bonus*: Calcula el promedio de los píxeles en la submatriz 4x4 del centro.



In [78]:
img = np.random.randint(0, 256, (10, 10))
img

array([[  2,  46, 125, 102, 151,  21, 233,   5, 127,  97],
       [ 51, 204, 238,  59,   4, 158, 171, 241,  64, 190],
       [212, 255, 230,  46, 246,  56, 250, 205, 108,  98],
       [114, 119,  89, 110, 100,  86,  52, 187,  92, 222],
       [171, 208, 158, 184, 122, 183, 249,  85, 243,  92],
       [ 49, 129, 112, 106, 121, 244, 255, 147,  87,  37],
       [193,  40, 115, 119, 200,   8,  70,  47,  58,  97],
       [218, 247, 104, 158, 141, 254,   2, 212, 171, 226],
       [166, 122, 138, 255, 183,  86, 217, 133, 253, 129],
       [ 48, 122,  50,  43,  31, 207,  56,  90,  79,  65]], dtype=int32)

In [66]:
# Esquina superior izquierda
upper_left = img[:3, :3]
print(upper_left)

[[149 253 191]
 [ 96 217 250]
 [180  32 252]]


In [67]:
# Fila central completa
central_col = img[:, 5]
central_col.reshape(-1, 1)

array([[242],
       [ 83],
       [255],
       [104],
       [246],
       [194],
       [ 56],
       [221],
       [ 92],
       [ 32]], dtype=int32)

In [70]:
img

array([[149, 253, 191, 207, 255, 242,  51,  41, 127,  10],
       [ 96, 217, 250,  18, 242,  83,   8, 163, 240,  85],
       [180,  32, 252,   7, 235, 255,  21,  92,  95,  13],
       [ 79, 242, 104, 250, 176, 104,  93,  70, 157,  48],
       [234, 237, 152,  48,  14, 246,  26, 253,  25, 231],
       [ 26,  14,  97, 226, 139, 194,  21, 174, 236, 147],
       [ 71, 207, 173, 203,  77,  56, 176, 132,  84,  20],
       [122, 112,  41, 216, 100, 221,  85,  25,  56, 147],
       [ 21,  42,   4,  22, 216,  92,  37,  93,  60, 113],
       [ 62,  14, 255,  18,  95,  32,  28, 193,  35,  24]], dtype=int32)

In [73]:
img[3:7, 3:7] = 0
img

array([[149, 253, 191, 207, 255, 242,  51,  41, 127,  10],
       [ 96, 217, 250,  18, 242,  83,   8, 163, 240,  85],
       [180,  32, 252,   7, 235, 255,  21,  92,  95,  13],
       [ 79, 242, 104,   0,   0,   0,   0,  70, 157,  48],
       [234, 237, 152,   0,   0,   0,   0, 253,  25, 231],
       [ 26,  14,  97,   0,   0,   0,   0, 174, 236, 147],
       [ 71, 207, 173,   0,   0,   0,   0, 132,  84,  20],
       [122, 112,  41, 216, 100, 221,  85,  25,  56, 147],
       [ 21,  42,   4,  22, 216,  92,  37,  93,  60, 113],
       [ 62,  14, 255,  18,  95,  32,  28, 193,  35,  24]], dtype=int32)

In [74]:
# Extrae el cuadro central de 3x3.

center_4x4 = img[3:7, 3:7]
center_4x4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [76]:
np.mean(center_4x4)

np.float64(0.0)

In [ ]:
# Crea una versión espejada horizontalmente de la imagen.
# 
horizontal_reflex = img[:, ::-1]
horizontal_reflex

array([[ 66, 115, 184,  49, 159,  87,   1, 233, 175, 225],
       [178, 161, 116,  44, 147, 135, 116, 103, 241, 235],
       [170,  70,  13,  31, 221, 145,   3, 124,  26, 155],
       [185, 114,  52, 159,  55, 135,  45,  65,  57, 238],
       [ 84, 140,  38,  62, 172, 146, 159,  29, 130, 236],
       [158,  62, 157,  25, 200, 191, 175, 212,  96, 173],
       [149,  73, 159,  89, 186,  91, 139, 198,  41,  51],
       [105, 240, 239, 102,  81, 226, 100, 100, 131,  34],
       [138, 159, 199, 145,  33,  37,  66, 155,   0, 237],
       [148, 182, 113, 164, 106, 182, 103, 238, 236, 202]], dtype=int32)

In [79]:
img

array([[  2,  46, 125, 102, 151,  21, 233,   5, 127,  97],
       [ 51, 204, 238,  59,   4, 158, 171, 241,  64, 190],
       [212, 255, 230,  46, 246,  56, 250, 205, 108,  98],
       [114, 119,  89, 110, 100,  86,  52, 187,  92, 222],
       [171, 208, 158, 184, 122, 183, 249,  85, 243,  92],
       [ 49, 129, 112, 106, 121, 244, 255, 147,  87,  37],
       [193,  40, 115, 119, 200,   8,  70,  47,  58,  97],
       [218, 247, 104, 158, 141, 254,   2, 212, 171, 226],
       [166, 122, 138, 255, 183,  86, 217, 133, 253, 129],
       [ 48, 122,  50,  43,  31, 207,  56,  90,  79,  65]], dtype=int32)

In [75]:
# Crea una versión rotada 90° en sentido horario.
def rotate_90_degrees(arr: np.ndarray):
    return arr.T[::-1, :]

In [80]:
print(rotate_90_degrees(img))

[[ 97 190  98 222  92  37  97 226 129  65]
 [127  64 108  92 243  87  58 171 253  79]
 [  5 241 205 187  85 147  47 212 133  90]
 [233 171 250  52 249 255  70   2 217  56]
 [ 21 158  56  86 183 244   8 254  86 207]
 [151   4 246 100 122 121 200 141 183  31]
 [102  59  46 110 184 106 119 158 255  43]
 [125 238 230  89 158 112 115 104 138  50]
 [ 46 204 255 119 208 129  40 247 122 122]
 [  2  51 212 114 171  49 193 218 166  48]]


#### Rotating practice

In [83]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
A.T[::-1, :]

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [90]:
np.rot90(A, k=-1)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

# Boolean masks

Cuando se aplica una condición a un array, NumPy devuelve un array booleano del mismo shape, con True donde la condición se cumple. 

In [2]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
result = a[mask] 
result

array([4, 5])

**Práctica**

Genera un array 1D de 20 enteros aleatorios entre 0 y 100. Filtra todos los elementos que sean pares y mayores que la mediana del array.

In [5]:
arr = np.random.randint(0, 100, 20)
arr

array([57, 54, 61, 31, 91, 51, 14, 30,  4, 96, 75,  1, 92,  0, 41, 43,  8,
       48, 18, 80], dtype=int32)

In [10]:
np.median(arr)

np.float64(45.5)

In [8]:
mask =  (arr % 2 == 0) & (arr > np.median(arr))
mask

array([False,  True, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True])

In [9]:
arr[mask]

array([54, 96, 92, 48, 80], dtype=int32)

**Ejercicio 1**: Números entre percentiles

Genera un array 1D de 50 valores flotantes aleatorios entre 0 y 1. Filtra todos los valores que estén entre el percentil 25 y 75.

*Hint*: Usa np.percentile.



In [16]:
arr = np.random.random(50)
arr

array([0.65548667, 0.18110136, 0.75840702, 0.88283412, 0.21210202,
       0.59129479, 0.22212184, 0.56654607, 0.3242446 , 0.97317797,
       0.69032044, 0.3062604 , 0.14068642, 0.83585733, 0.00414706,
       0.8709351 , 0.96325502, 0.32332681, 0.47804948, 0.57622323,
       0.79283536, 0.51868083, 0.38943034, 0.41133883, 0.28986522,
       0.01699074, 0.57750731, 0.47917905, 0.45258569, 0.55245296,
       0.81897201, 0.46322157, 0.34719486, 0.00679068, 0.42323428,
       0.55091154, 0.64059958, 0.67852409, 0.23615281, 0.28010862,
       0.28452952, 0.32897992, 0.74517467, 0.26007071, 0.43880256,
       0.31740607, 0.97845783, 0.09117445, 0.42047901, 0.9061417 ])

In [24]:
percent_25 = np.percentile(arr, 25)
print('25%', percent_25)
percent_75 = np.percentile(arr, 75)
print('75%', percent_75)
mask = (arr >= percent_25) & (arr <= percent_75)
np.sort(arr[mask])

25% 0.29396401225717395
75% 0.6727647325324295


array([0.3062604 , 0.31740607, 0.32332681, 0.3242446 , 0.32897992,
       0.34719486, 0.38943034, 0.41133883, 0.42047901, 0.42323428,
       0.43880256, 0.45258569, 0.46322157, 0.47804948, 0.47917905,
       0.51868083, 0.55091154, 0.55245296, 0.56654607, 0.57622323,
       0.57750731, 0.59129479, 0.64059958, 0.65548667])

**Ejercicio 2**: Reemplazar por condiciones

Dado un array de enteros aleatorios de tamaño (6, 6) entre 0 y 100, reemplaza todos los valores impares menores que 50 por -1.



In [25]:
arr = np.random.randint(0, 100, size=(6, 6))
arr

array([[28, 62, 61, 55, 85, 71],
       [23, 96, 90, 28, 89, 70],
       [70, 90,  0, 33, 76, 64],
       [58, 18, 70, 95,  4,  2],
       [99, 23, 83, 76, 40,  9],
       [39, 92, 33, 94, 41, 45]], dtype=int32)

In [26]:
mask = arr < 50
arr[mask] = -1
arr

array([[-1, 62, 61, 55, 85, 71],
       [-1, 96, 90, -1, 89, 70],
       [70, 90, -1, -1, 76, 64],
       [58, -1, 70, 95, -1, -1],
       [99, -1, 83, 76, -1, -1],
       [-1, 92, -1, 94, -1, -1]], dtype=int32)

**Ejercicio 3**: Índices de valores cercanos

Dado un array flotante de 100 valores entre 0 y 10, encuentra los índices de los valores que están a menos de 0.5 del valor 5.0.

*Hint*: np.abs(arr - 5.0) < 0.5 + np.where(...)



In [40]:
arr = np.random.uniform(0, 10, 100)
arr

array([2.79685075, 4.67608801, 8.5968692 , 5.17511106, 3.53274338,
       9.77822283, 7.0745695 , 3.73509452, 1.36447902, 1.66257296,
       6.74892903, 1.74110313, 5.64377059, 1.23786474, 7.10541588,
       0.57146236, 3.01962105, 0.31372692, 8.09086305, 5.33554742,
       1.58352555, 1.49222621, 1.28388953, 5.46735566, 7.30972806,
       2.5911214 , 2.1091373 , 9.90767771, 4.70189222, 9.8395836 ,
       3.89118233, 5.94024904, 5.47624072, 2.93273147, 2.02522196,
       7.1559087 , 1.39196251, 9.40696752, 4.40841356, 4.40933471,
       7.72269085, 4.76264924, 3.19313757, 6.98945631, 9.18880478,
       3.90150609, 8.66401264, 2.60224985, 7.39848093, 2.24569168,
       2.32484044, 2.03800708, 4.80456235, 5.64718968, 2.22605071,
       2.14788675, 4.56939088, 8.83700384, 3.28683316, 7.01279537,
       4.71379547, 6.14795171, 2.35388751, 7.24442037, 2.51716397,
       6.70534173, 7.73927537, 5.8753676 , 7.9846457 , 5.81193461,
       4.17043922, 6.13176962, 8.87819388, 7.7229952 , 9.65632

In [41]:
mask = np.abs(arr - 5.0) < 0.5
mask

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False])

In [42]:
np.where(mask)  # return indices satisfying the mask condition

(array([ 1,  3, 19, 23, 28, 32, 41, 52, 56, 60, 91]),)